from __future__ import annotations

import json
import logging
import platform
import shutil
import subprocess
import tempfile
import uuid
import zipfile
from pathlib import Path

import numpy as np

from surrogate_tool.contracts.run_config import load_run_config
from surrogate_tool.contracts.status import write_status
from surrogate_tool.paths import runs_root

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _utc_now() -> str:
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _resolve_gcc(cfg_gcc_path: str | None) -> str | None:
    """
    Locate gcc in priority order:
      1. OpenModelica bundled MinGW  (C:/OpenModelica*/tools/msys/mingw64/bin/gcc.exe)
      2. System PATH  (shutil.which)
      3. cfg.gcc_path  (explicit user override)
    Returns the path string if found, None otherwise.
    """
    import glob

    # 1 — OpenModelica bundled gcc (search all installed versions and locations)
    # OM 1.24+ (ucrt64) and older (mingw64) are both searched.
    # Also covers OneDrive/Documents installs (non-standard location).
    home = Path.home()
    # Build root globs: standard C:\ locations + OneDrive variants + user Documents
    om_root_patterns = [
        r"C:\OpenModelica*",
        r"C:\Program Files\OpenModelica*",
        r"C:\Program Files (x86)\OpenModelica*",
        str(home / "Documents" / "OpenModelica*"),
    ]
    # Also add every OneDrive-style folder under the user home
    for od in home.glob("OneDrive*"):
        om_root_patterns.append(str(od / "Documents" / "OpenModelica*"))

    gcc_suffixes = [
        r"tools\msys\ucrt64\bin\gcc.exe",   # OM 1.24+ preferred
        r"tools\msys\mingw64\bin\gcc.exe",  # OM older
    ]

    om_candidates: list[str] = []
    for root_pat in om_root_patterns:
        for suffix in gcc_suffixes:
            om_candidates.extend(glob.glob(str(Path(root_pat) / suffix)))

    if om_candidates:
        # sort descending so latest version string is first
        om_candidates.sort(reverse=True)
        log.info("FMU: using OpenModelica bundled gcc: %s", om_candidates[0])
        return om_candidates[0]

    # 2 — system PATH
    path_gcc = shutil.which("gcc")
    if path_gcc:
        log.info("FMU: using system gcc from PATH: %s", path_gcc)
        return path_gcc

    # 3 — explicit override from RunConfig
    if cfg_gcc_path:
        p = Path(cfg_gcc_path)
        if p.exists():
            log.info("FMU: using user-configured gcc: %s", cfg_gcc_path)
            return str(p)
        else:
            log.warning("FMU: cfg.gcc_path set to '%s' but file not found.", cfg_gcc_path)

    return None


# ---------------------------------------------------------------------------
# modelDescription.xml
# ---------------------------------------------------------------------------

def _gen_model_description_xml(
    pkg_name: str,
    input_cols: list[str],
    output_cols: list[str],
    guid: str,
) -> str:
    n_in = len(input_cols)
    n_out = len(output_cols)

    sv_lines: list[str] = []
    # inputs: vr 0 .. n_in-1
    # FMI 2.0: continuous inputs must NOT carry initial="exact"; <Real> requires start attribute
    for i, col in enumerate(input_cols):
        sv_lines.append(
            f'    <ScalarVariable name="{col}" valueReference="{i}" '
            f'causality="input" variability="continuous">'
            f'\n      <Real start="0.0"/>\n    </ScalarVariable>'
        )
    # outputs: vr n_in .. n_in+n_out-1
    dep_str = " ".join(str(i + 1) for i in range(n_in))  # 1-based indices per FMI 2.0 spec
    for j, col in enumerate(output_cols):
        vr = n_in + j
        sv_lines.append(
            f'    <ScalarVariable name="{col}" valueReference="{vr}" '
            f'causality="output" variability="continuous" initial="calculated">'
            f'\n      <Real/>\n    </ScalarVariable>'
        )

    unknowns: list[str] = []
    for k in range(1, n_out + 1):
        idx = n_in + k  # 1-based index in ScalarVariable list
        unknowns.append(
            f'      <Unknown index="{idx}" dependencies="{dep_str}"/>'
        )

    xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<fmiModelDescription
  fmiVersion="2.0"
  modelName="{pkg_name}"
  guid="{{{guid}}}"
  description="MLP surrogate model generated by SurrogateGenerator"
  generationTool="SurrogateGenerator"
  generationDateAndTime="{_utc_now()}"
  variableNamingConvention="flat"
  numberOfEventIndicators="0">

  <ModelExchange modelIdentifier="{pkg_name}"/>

  <LogCategories>
    <Category name="logAll"/>
    <Category name="logStatusError"/>
  </LogCategories>

  <ModelVariables>
{chr(10).join(sv_lines)}
  </ModelVariables>

  <ModelStructure>
    <Outputs>
{chr(10).join(unknowns)}
    </Outputs>
  </ModelStructure>

</fmiModelDescription>
"""
    return xml


# ---------------------------------------------------------------------------
# model.c  — FMI 2.0 Model Exchange, pure algebraic MLP
# ---------------------------------------------------------------------------

def _c_array_1d(values: list[float], name: str) -> str:
    vals = ", ".join(f"{v:.17g}" for v in values)
    return f"static const double {name}[] = {{{vals}}};"


def _c_array_2d_flat(rows: list[list[float]], name: str) -> str:
    """Emit a flat row-major C array for a 2-D matrix."""
    flat = []
    for row in rows:
        flat.extend(row)
    vals = ", ".join(f"{v:.17g}" for v in flat)
    n_rows = len(rows)
    n_cols = len(rows[0]) if rows else 0
    return f"/* shape [{n_rows}][{n_cols}] row-major */\nstatic const double {name}[] = {{{vals}}};"


def _gen_model_c(
    pkg_name: str,
    input_cols: list[str],
    output_cols: list[str],
    export: dict,
) -> str:
    n_in = len(input_cols)
    n_out = len(output_cols)
    layers: list[dict] = export["layers"]

    # Build C static data for each layer
    layer_data_lines: list[str] = []
    for li, layer in enumerate(layers):
        # Keras stores W as [n_in, n_out]; C matmul expects row i = output neuron i
        # so we must transpose to [n_out, n_in] before flattening row-major.
        W_T = np.array(layer["W"]).T.tolist()  # [n_out, n_in]
        b = layer["b"]   # list[float]
        layer_data_lines.append(_c_array_2d_flat(W_T, f"L{li}_W"))
        layer_data_lines.append(_c_array_1d(b, f"L{li}_b"))

    # x_scaler: mean + scale arrays
    xs = export["x_scaler"]
    ys = export["y_scaler"]
    layer_data_lines.append(_c_array_1d(xs["mean"], "X_MEAN"))
    layer_data_lines.append(_c_array_1d(xs["scale"], "X_SCALE"))
    layer_data_lines.append(_c_array_1d(ys["mean"], "Y_MEAN"))
    layer_data_lines.append(_c_array_1d(ys["scale"], "Y_SCALE"))

    # Build _compute() body
    # intermediate buffer sizing: find max neurons
    layer_sizes = []
    for layer in layers:
        layer_sizes.append(len(layer["b"]))
    max_neurons = max(layer_sizes + [n_in])

    compute_lines: list[str] = []
    compute_lines.append(f"  double tmp[{max_neurons}];")
    compute_lines.append(f"  double buf[{max_neurons}];")
    compute_lines.append(f"  int i, j;")
    compute_lines.append("")
    # scale inputs into tmp
    compute_lines.append(f"  for (i = 0; i < {n_in}; i++) {{")
    compute_lines.append(f"    tmp[i] = (inst->u[i] - X_MEAN[i]) / X_SCALE[i];")
    compute_lines.append(f"  }}")

    prev_size = n_in
    for li, layer in enumerate(layers):
        W = layer["W"]
        act = (layer.get("activation") or "linear").lower()
        n_neurons = len(layer["b"])
        compute_lines.append(f"  /* Layer {li}: [{prev_size}] -> [{n_neurons}], act={act} */")
        compute_lines.append(f"  for (i = 0; i < {n_neurons}; i++) {{")
        compute_lines.append(f"    buf[i] = L{li}_b[i];")
        compute_lines.append(f"    for (j = 0; j < {prev_size}; j++) {{")
        compute_lines.append(f"      buf[i] += L{li}_W[i * {prev_size} + j] * tmp[j];")
        compute_lines.append(f"    }}")
        if act == "relu":
            compute_lines.append(f"    buf[i] = buf[i] > 0.0 ? buf[i] : 0.0;")
        compute_lines.append(f"  }}")
        compute_lines.append(f"  for (i = 0; i < {n_neurons}; i++) tmp[i] = buf[i];")
        prev_size = n_neurons

    # unscale outputs (last layer size == n_out)
    compute_lines.append(f"  for (i = 0; i < {n_out}; i++) {{")
    compute_lines.append(f"    inst->y[i] = tmp[i] * Y_SCALE[i] + Y_MEAN[i];")
    compute_lines.append(f"  }}")

    compute_body = "\n".join(compute_lines)
    layer_data = "\n".join(layer_data_lines)

    c_src = f"""/*
 * FMU 2.0 Model Exchange — {pkg_name}
 * MLP surrogate generated by SurrogateGenerator
 * DO NOT EDIT — auto-generated file
 *
 * n_inputs  = {n_in}   ({', '.join(input_cols)})
 * n_outputs = {n_out}  ({', '.join(output_cols)})
 * n_layers  = {len(layers)}
 */

/* ---- Inline FMI 2.0 type definitions (no separate headers needed) ---- */
#include <stdlib.h>
#include <string.h>

typedef void*       fmi2Component;
typedef void*       fmi2ComponentEnvironment;
typedef const char* fmi2String;
typedef double      fmi2Real;
typedef int         fmi2Integer;
typedef int         fmi2Boolean;
typedef void*       fmi2FMUstate;
typedef unsigned int fmi2ValueReference;
typedef unsigned char fmi2Byte;

typedef enum {{
    fmi2OK = 0,
    fmi2Warning,
    fmi2Discard,
    fmi2Error,
    fmi2Fatal,
    fmi2Pending
}} fmi2Status;

typedef enum {{
    fmi2ModelExchange = 0,
    fmi2CoSimulation
}} fmi2Type;

typedef struct {{
    void (*logger)(fmi2ComponentEnvironment, fmi2String, fmi2Status, fmi2String, fmi2String, ...);
    void* (*allocateMemory)(size_t, size_t);
    void  (*freeMemory)(void*);
    void  (*stepFinished)(fmi2ComponentEnvironment, fmi2Status);
    fmi2ComponentEnvironment componentEnvironment;
}} fmi2CallbackFunctions;

typedef struct {{
    fmi2Boolean newDiscreteStatesNeeded;
    fmi2Boolean terminateSimulation;
    fmi2Boolean nominalsOfContinuousStatesChanged;
    fmi2Boolean valuesOfContinuousStatesChanged;
    fmi2Boolean nextEventTimeDefined;
    fmi2Real    nextEventTime;
}} fmi2EventInfo;

#define fmi2True  1
#define fmi2False 0

/* ---- DLL export macro ---- */
#if defined(_WIN32) || defined(_WIN64)
  #define FMI2_Export __declspec(dllexport)
#else
  #define FMI2_Export __attribute__((visibility("default")))
#endif

/* ---- Model instance ---- */
typedef struct {{
    double u[{n_in}];
    double y[{n_out}];
    int isDirty;
}} ModelInstance;

/* ---- Static network weights ---- */
{layer_data}

/* ---- Forward pass ---- */
static void _compute(ModelInstance* inst) {{
{compute_body}
  inst->isDirty = 0;
}}

/* ================================================================
   FMI 2.0 Model Exchange API
   ================================================================ */

FMI2_Export const char* fmi2GetTypesPlatform(void) {{
    return "default";
}}

FMI2_Export const char* fmi2GetVersion(void) {{
    return "2.0";
}}

FMI2_Export fmi2Status fmi2SetDebugLogging(
    fmi2Component c, fmi2Boolean loggingOn,
    size_t nCategories, const fmi2String categories[]) {{
    (void)c; (void)loggingOn; (void)nCategories; (void)categories;
    return fmi2OK;
}}

FMI2_Export fmi2Component fmi2Instantiate(
    fmi2String instanceName, fmi2Type fmuType,
    fmi2String fmuGUID, fmi2String fmuResourceLocation,
    const fmi2CallbackFunctions* functions,
    fmi2Boolean visible, fmi2Boolean loggingOn) {{
    (void)instanceName; (void)fmuType; (void)fmuGUID;
    (void)fmuResourceLocation; (void)visible; (void)loggingOn;
    ModelInstance* inst;
    if (functions && functions->allocateMemory)
        inst = (ModelInstance*)functions->allocateMemory(1, sizeof(ModelInstance));
    else
        inst = (ModelInstance*)calloc(1, sizeof(ModelInstance));
    if (!inst) return NULL;
    memset(inst, 0, sizeof(ModelInstance));
    inst->isDirty = 1;
    return (fmi2Component)inst;
}}

FMI2_Export void fmi2FreeInstance(fmi2Component c) {{
    if (c) free(c);
}}

FMI2_Export fmi2Status fmi2SetupExperiment(
    fmi2Component c, fmi2Boolean toleranceDefined, fmi2Real tolerance,
    fmi2Real startTime, fmi2Boolean stopTimeDefined, fmi2Real stopTime) {{
    (void)c; (void)toleranceDefined; (void)tolerance;
    (void)startTime; (void)stopTimeDefined; (void)stopTime;
    return fmi2OK;
}}

FMI2_Export fmi2Status fmi2EnterInitializationMode(fmi2Component c) {{
    (void)c;
    return fmi2OK;
}}

FMI2_Export fmi2Status fmi2ExitInitializationMode(fmi2Component c) {{
    ModelInstance* inst = (ModelInstance*)c;
    _compute(inst);
    return fmi2OK;
}}

FMI2_Export fmi2Status fmi2Terminate(fmi2Component c) {{
    (void)c;
    return fmi2OK;
}}

FMI2_Export fmi2Status fmi2Reset(fmi2Component c) {{
    ModelInstance* inst = (ModelInstance*)c;
    memset(inst->u, 0, sizeof(inst->u));
    memset(inst->y, 0, sizeof(inst->y));
    inst->isDirty = 1;
    return fmi2OK;
}}

FMI2_Export fmi2Status fmi2GetReal(
    fmi2Component c, const fmi2ValueReference vr[], size_t nvr, fmi2Real value[]) {{
    ModelInstance* inst = (ModelInstance*)c;
    if (inst->isDirty) _compute(inst);
    size_t i;
    for (i = 0; i < nvr; i++) {{
        if (vr[i] < {n_in}) {{
            value[i] = inst->u[vr[i]];
        }} else if (vr[i] < {n_in + n_out}) {{
            value[i] = inst->y[vr[i] - {n_in}];
        }} else {{
            return fmi2Error;
        }}
    }}
    return fmi2OK;
}}

FMI2_Export fmi2Status fmi2SetReal(
    fmi2Component c, const fmi2ValueReference vr[], size_t nvr, const fmi2Real value[]) {{
    ModelInstance* inst = (ModelInstance*)c;
    size_t i;
    for (i = 0; i < nvr; i++) {{
        if (vr[i] < {n_in}) {{
            inst->u[vr[i]] = value[i];
            inst->isDirty = 1;
        }} else {{
            return fmi2Error;
        }}
    }}
    return fmi2OK;
}}

FMI2_Export fmi2Status fmi2GetInteger(
    fmi2Component c, const fmi2ValueReference vr[], size_t nvr, fmi2Integer value[]) {{
    (void)c; (void)vr; (void)nvr; (void)value;
    return fmi2Error;
}}
FMI2_Export fmi2Status fmi2SetInteger(
    fmi2Component c, const fmi2ValueReference vr[], size_t nvr, const fmi2Integer value[]) {{
    (void)c; (void)vr; (void)nvr; (void)value;
    return fmi2Error;
}}
FMI2_Export fmi2Status fmi2GetBoolean(
    fmi2Component c, const fmi2ValueReference vr[], size_t nvr, fmi2Boolean value[]) {{
    (void)c; (void)vr; (void)nvr; (void)value;
    return fmi2Error;
}}
FMI2_Export fmi2Status fmi2SetBoolean(
    fmi2Component c, const fmi2ValueReference vr[], size_t nvr, const fmi2Boolean value[]) {{
    (void)c; (void)vr; (void)nvr; (void)value;
    return fmi2Error;
}}
FMI2_Export fmi2Status fmi2GetString(
    fmi2Component c, const fmi2ValueReference vr[], size_t nvr, fmi2String value[]) {{
    (void)c; (void)vr; (void)nvr; (void)value;
    return fmi2Error;
}}
FMI2_Export fmi2Status fmi2SetString(
    fmi2Component c, const fmi2ValueReference vr[], size_t nvr, const fmi2String value[]) {{
    (void)c; (void)vr; (void)nvr; (void)value;
    return fmi2Error;
}}

/* Model Exchange — state/derivative stubs (pure algebraic: 0 states) */

FMI2_Export fmi2Status fmi2EnterEventMode(fmi2Component c) {{
    (void)c; return fmi2OK;
}}

FMI2_Export fmi2Status fmi2NewDiscreteStates(fmi2Component c, fmi2EventInfo* ei) {{
    (void)c;
    ei->newDiscreteStatesNeeded           = fmi2False;
    ei->terminateSimulation               = fmi2False;
    ei->nominalsOfContinuousStatesChanged = fmi2False;
    ei->valuesOfContinuousStatesChanged   = fmi2False;
    ei->nextEventTimeDefined              = fmi2False;
    ei->nextEventTime                     = 0.0;
    return fmi2OK;
}}

FMI2_Export fmi2Status fmi2EnterContinuousTimeMode(fmi2Component c) {{
    (void)c; return fmi2OK;
}}

FMI2_Export fmi2Status fmi2CompletedIntegratorStep(
    fmi2Component c, fmi2Boolean noSetFMUStatePriorToCurrentPoint,
    fmi2Boolean* enterEventMode, fmi2Boolean* terminateSimulation) {{
    (void)c; (void)noSetFMUStatePriorToCurrentPoint;
    *enterEventMode       = fmi2False;
    *terminateSimulation  = fmi2False;
    return fmi2OK;
}}

FMI2_Export fmi2Status fmi2SetTime(fmi2Component c, fmi2Real time) {{
    (void)c; (void)time; return fmi2OK;
}}

FMI2_Export fmi2Status fmi2SetContinuousStates(
    fmi2Component c, const fmi2Real x[], size_t nx) {{
    (void)c; (void)x; (void)nx; return fmi2OK;
}}

FMI2_Export fmi2Status fmi2GetDerivatives(
    fmi2Component c, fmi2Real derivatives[], size_t nx) {{
    (void)c; (void)nx;
    /* no continuous states */
    (void)derivatives;
    return fmi2OK;
}}

FMI2_Export fmi2Status fmi2GetEventIndicators(
    fmi2Component c, fmi2Real eventIndicators[], size_t ni) {{
    (void)c; (void)ni;
    (void)eventIndicators;
    return fmi2OK;
}}

FMI2_Export fmi2Status fmi2GetContinuousStates(
    fmi2Component c, fmi2Real x[], size_t nx) {{
    (void)c; (void)nx;
    (void)x;
    return fmi2OK;
}}

FMI2_Export fmi2Status fmi2GetNominalsOfContinuousStates(
    fmi2Component c, fmi2Real x_nominal[], size_t nx) {{
    (void)c; (void)nx;
    (void)x_nominal;
    return fmi2OK;
}}

/* FMUState serialisation — not supported */
FMI2_Export fmi2Status fmi2GetFMUstate(fmi2Component c, fmi2FMUstate* s) {{
    (void)c; (void)s; return fmi2Error;
}}
FMI2_Export fmi2Status fmi2SetFMUstate(fmi2Component c, fmi2FMUstate s) {{
    (void)c; (void)s; return fmi2Error;
}}
FMI2_Export fmi2Status fmi2FreeFMUstate(fmi2Component c, fmi2FMUstate* s) {{
    (void)c; (void)s; return fmi2Error;
}}
FMI2_Export fmi2Status fmi2SerializedFMUstateSize(fmi2Component c, fmi2FMUstate s, size_t* sz) {{
    (void)c; (void)s; (void)sz; return fmi2Error;
}}
FMI2_Export fmi2Status fmi2SerializeFMUstate(fmi2Component c, fmi2FMUstate s, fmi2Byte b[], size_t sz) {{
    (void)c; (void)s; (void)b; (void)sz; return fmi2Error;
}}
FMI2_Export fmi2Status fmi2DeSerializeFMUstate(fmi2Component c, const fmi2Byte b[], size_t sz, fmi2FMUstate* s) {{
    (void)c; (void)b; (void)sz; (void)s; return fmi2Error;
}}

FMI2_Export fmi2Status fmi2GetDirectionalDerivative(
    fmi2Component c,
    const fmi2ValueReference vUnknown_ref[], size_t nUnknown,
    const fmi2ValueReference vKnown_ref[],   size_t nKnown,
    const fmi2Real dvKnown[], fmi2Real dvUnknown[]) {{
    (void)c; (void)vUnknown_ref; (void)nUnknown;
    (void)vKnown_ref; (void)nKnown;
    (void)dvKnown; (void)dvUnknown;
    return fmi2Error;
}}
"""
    return c_src


# ---------------------------------------------------------------------------
# DLL compilation
# ---------------------------------------------------------------------------

def _compile_dll(
    model_c_src: str,
    pkg_name: str,
    gcc_exe: str,
    out_dir: Path,
) -> Path | None:
    """
    Compile model.c -> <pkg_name>.dll using the provided gcc executable.
    Returns path to the .dll on success, None on failure.
    """
    import os

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        c_file = tmp_path / "model.c"
        dll_out = tmp_path / f"{pkg_name}.dll"
        c_file.write_text(model_c_src, encoding="utf-8")

        cmd = [
            gcc_exe,
            "-shared",
            "-fPIC",
            "-O2",
            "-DFMI2_FUNCTION_PREFIX=",
            "-o", str(dll_out),
            str(c_file),
        ]

        # Ensure gcc's own bin directory is on PATH so it can locate cc1/as/ld
        env = os.environ.copy()
        gcc_bin_dir = str(Path(gcc_exe).parent)
        existing_path = env.get("PATH", "")
        if gcc_bin_dir.lower() not in existing_path.lower():
            env["PATH"] = gcc_bin_dir + os.pathsep + existing_path

        log.info("FMU: compiling DLL: %s", " ".join(cmd))
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=120,
                env=env,
            )
        except FileNotFoundError:
            log.error("FMU: gcc not found at '%s'", gcc_exe)
            return None
        except subprocess.TimeoutExpired:
            log.error("FMU: gcc compilation timed out.")
            return None

        if result.returncode != 0:
            log.error("FMU: gcc compilation failed (rc=%d):\n%s\n%s",
                      result.returncode, result.stdout, result.stderr)
            return None

        if not dll_out.exists():
            log.error("FMU: gcc reported success but DLL not found at %s", dll_out)
            return None

        out_dir.mkdir(parents=True, exist_ok=True)
        dest = out_dir / f"{pkg_name}.dll"
        shutil.copy2(dll_out, dest)
        log.info("FMU: DLL compiled successfully → %s", dest)
        return dest


# ---------------------------------------------------------------------------
# Pack .fmu zip
# ---------------------------------------------------------------------------

def _pack_fmu(
    fmu_path: Path,
    xml: str,
    model_c: str,
    dll_path: Path | None,
    pkg_name: str,
) -> None:
    fmu_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(fmu_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("modelDescription.xml", xml.encode("utf-8"))
        zf.writestr(f"sources/model.c", model_c.encode("utf-8"))
        if dll_path and dll_path.exists():
            zf.write(dll_path, f"binaries/win64/{pkg_name}.dll")
    log.info("FMU: packed → %s", fmu_path)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def create_fmu(run_id: str, attempt_num: int) -> dict:
    """
    Stage 5b: Generate FMU 2.0 Model Exchange from mlp_weights.json.

    Output:
        runs/<run_id>/attempts/attempt_XXX/fmu/<PackageName>.fmu
          ├── modelDescription.xml
          ├── sources/model.c
          └── binaries/win64/<PackageName>.dll   (if gcc found)
    """
    run_dir = runs_root() / run_id
    cfg_path = run_dir / "input" / "run_config.json"
    if not cfg_path.exists():
        raise FileNotFoundError(f"run_config.json not found: {cfg_path}")

    cfg = load_run_config(cfg_path)
    status_path = run_dir / "status.json"

    write_status(status_path, state="CREATE_FMU", message="Creating FMU 2.0 Model Exchange...", progress=0.75)

    attempt_dir = run_dir / "attempts" / f"attempt_{attempt_num:03d}"
    weights_path = attempt_dir / "processed" / "mlp_weights.json"
    if not weights_path.exists():
        raise FileNotFoundError(f"mlp_weights.json not found: {weights_path}. Run training first.")

    export = json.loads(weights_path.read_text(encoding="utf-8"))

    pkg_name = cfg.package_name
    input_cols = cfg.input_columns
    output_cols = cfg.output_columns

    fmu_dir = attempt_dir / "fmu"
    fmu_dir.mkdir(parents=True, exist_ok=True)

    # --- Generate artifacts ---
    write_status(status_path, state="CREATE_FMU", message="Generating modelDescription.xml...", progress=0.77)
    run_guid = str(uuid.uuid4())
    xml = _gen_model_description_xml(pkg_name, input_cols, output_cols, run_guid)

    write_status(status_path, state="CREATE_FMU", message="Generating model.c (MLP forward pass)...", progress=0.79)
    model_c = _gen_model_c(pkg_name, input_cols, output_cols, export)

    # --- Compile DLL ---
    gcc_exe = _resolve_gcc(getattr(cfg, "gcc_path", None))
    dll_path: Path | None = None

    if gcc_exe:
        write_status(status_path, state="CREATE_FMU", message="Compiling Windows DLL via gcc...", progress=0.81)
        dll_path = _compile_dll(model_c, pkg_name, gcc_exe, fmu_dir / "binaries" / "win64")
        if dll_path is None:
            msg = (
                "FMU DLL compilation failed. "
                "FMU will be source-only — OpenModelica may need to compile it on import. "
                "Check pipeline.log for gcc error details."
            )
            log.warning(msg)
            write_status(status_path, state="CREATE_FMU", message=msg, progress=0.81)
    else:
        msg = (
            "gcc not found. FMU will be source-only (no binaries/win64/ DLL). "
            "To enable pre-compiled binary, install OpenModelica — gcc is auto-detected from: "
            r"C:\OpenModelica*\tools\msys\ucrt64\bin\gcc.exe (OM 1.24+) "
            r"or ~\OneDrive*\Documents\OpenModelica*\tools\msys\ucrt64\bin\gcc.exe. "
            "Alternatively set gcc_path in RunConfig."
        )
        log.warning(msg)
        write_status(status_path, state="CREATE_FMU", message=msg, progress=0.81)

    # --- Pack .fmu ---
    write_status(status_path, state="CREATE_FMU", message="Packing .fmu archive...", progress=0.82)
    fmu_path = fmu_dir / f"{pkg_name}.fmu"
    _pack_fmu(fmu_path, xml, model_c, dll_path, pkg_name)

    has_binary = dll_path is not None and dll_path.exists()
    write_status(
        status_path,
        state="CREATE_FMU_DONE",
        message=f"FMU created: {fmu_path.name} ({'with DLL' if has_binary else 'source-only'})",
        progress=0.83,
    )

    return {
        "timestamp_utc": _utc_now(),
        "run_id": run_id,
        "attempt": f"attempt_{attempt_num:03d}",
        "package_name": pkg_name,
        "fmu_path": str(fmu_path),
        "has_binary": has_binary,
        "gcc_used": gcc_exe,
    }
