from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from surrogate_tool.contracts.run_config import load_run_config
from surrogate_tool.contracts.status import write_status
from surrogate_tool.paths import runs_root


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _safe_read_json(path: Path) -> dict | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        try:
            return json.loads(path.read_text(encoding="utf-8-sig"))
        except Exception:
            return None


def _plot_loss_curves(train_history_csv: Path, out_png: Path) -> bool:
    if not train_history_csv.exists():
        return False
    df = pd.read_csv(train_history_csv)
    if "loss" not in df.columns:
        return False

    plt.figure(figsize=(8.5, 4.5))
    plt.plot(df["loss"].values, label="train_loss")
    if "val_loss" in df.columns:
        plt.plot(df["val_loss"].values, label="val_loss")
    plt.title("Training Loss Curves")
    plt.xlabel("Epoch")
    plt.ylabel("MSE (scaled)")
    plt.grid(True, alpha=0.3)
    plt.legend()
    out_png.parent.mkdir(parents=True, exist_ok=True)
    plt.tight_layout()
    plt.savefig(out_png, dpi=160)
    plt.close()
    return True


def _relpath(from_dir: Path, target: Path) -> str:
    try:
        return str(target.relative_to(from_dir)).replace("\\", "/")
    except Exception:
        return str(target).replace("\\", "/")


def _copy_report_backup(
    *,
    reports_dir: Path,
    modelica_pkg_dir: Path,
) -> dict:
    """
    Copy report artifacts into the Modelica package folder for easy access:
      modelica/<PackageName>/Report/
        report.html
        loss_curves.png
        metrics.json
        eda_profile.json
        figures/...
    """
    backup_dir = modelica_pkg_dir / "Report"
    backup_fig_dir = backup_dir / "figures"
    backup_dir.mkdir(parents=True, exist_ok=True)
    backup_fig_dir.mkdir(parents=True, exist_ok=True)

    copied = {}

    def _cp(src: Path, dst: Path):
        if src.exists():
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            copied[src.name] = str(dst)

    # Core report artifacts
    _cp(reports_dir / "report.html", backup_dir / "report.html")
    _cp(reports_dir / "loss_curves.png", backup_dir / "loss_curves.png")
    _cp(reports_dir / "metrics.json", backup_dir / "metrics.json")
    _cp(reports_dir / "train_history.csv", backup_dir / "train_history.csv")

    # Helpful analysis context
    _cp(reports_dir / "eda_profile.json", backup_dir / "eda_profile.json")
    _cp(reports_dir / "split_scale_report.json", backup_dir / "split_scale_report.json")
    _cp(reports_dir / "preprocess_report.json", backup_dir / "preprocess_report.json")

    # Copy EDA figure gallery (if exists)
    fig_src_dir = reports_dir / "figures"
    if fig_src_dir.exists():
        for p in fig_src_dir.glob("*.png"):
            _cp(p, backup_fig_dir / p.name)

    # Add a tiny README for clarity
    readme = backup_dir / "README.txt"
    readme.write_text(
        "This folder is a backup of the HTML report and key artifacts generated by the surrogate tool.\n"
        "Open report.html in a browser for the summary.\n",
        encoding="utf-8"
    )

    return {
        "backup_dir": str(backup_dir),
        "copied_files": copied,
    }


def generate_report(run_id: str, attempt_num: int) -> dict:
    """
    Produces an offline HTML report for engineers:
      attempts/attempt_###/reports/report.html

    NEW (Checkpoint 10.2):
      also copies report + key artifacts into:
      attempts/attempt_###/modelica/<PackageName>/Report/
    """
    run_dir = runs_root() / run_id
    cfg_path = run_dir / "input" / "run_config.json"
    if not cfg_path.exists():
        raise FileNotFoundError(f"run_config.json not found at: {cfg_path}")

    cfg = load_run_config(cfg_path)

    attempt_dir = run_dir / "attempts" / f"attempt_{attempt_num:03d}"
    processed_dir = attempt_dir / "processed"
    reports_dir = attempt_dir / "reports"
    figures_dir = reports_dir / "figures"
    modelica_pkg_dir = attempt_dir / "modelica" / cfg.package_name

    reports_dir.mkdir(parents=True, exist_ok=True)

    status_path = run_dir / "status.json"
    write_status(status_path, state="REPORT", message="Generating HTML report...", progress=0.2)

    # Load artifacts if present
    metrics = _safe_read_json(reports_dir / "metrics.json")
    train_history_csv = reports_dir / "train_history.csv"
    loss_png = reports_dir / "loss_curves.png"
    loss_ok = _plot_loss_curves(train_history_csv, loss_png)

    # Collect EDA images
    eda_imgs = []
    if figures_dir.exists():
        eda_imgs = sorted(figures_dir.glob("*.png"))

    # Artifact pointers
    model_path = processed_dir / "surrogate_model.keras"
    weights_path = processed_dir / "mlp_weights.json"
    surrogate_mo = modelica_pkg_dir / "Networks" / "SurrogateMLP.mo"
    package_mo = modelica_pkg_dir / "package.mo"

    # Build metrics table
    metrics_rows = ""
    if metrics and "output_columns" in metrics:
        outs = metrics.get("output_columns", [])
        rmse_s = metrics.get("metrics_scaled", {}).get("rmse_per_output", [])
        mae_s = metrics.get("metrics_scaled", {}).get("mae_per_output", [])
        rmse_p = metrics.get("metrics_physical", {}).get("rmse_per_output", [])
        mae_p = metrics.get("metrics_physical", {}).get("mae_per_output", [])

        def _get(arr, idx):
            try:
                return arr[idx]
            except Exception:
                return None

        for i, name in enumerate(outs):
            metrics_rows += f"""
            <tr>
              <td>{name}</td>
              <td>{_get(rmse_p,i)}</td>
              <td>{_get(mae_p,i)}</td>
              <td>{_get(rmse_s,i)}</td>
              <td>{_get(mae_s,i)}</td>
            </tr>
            """

    # HTML content
    loss_html = ""
    if loss_ok:
        loss_html = f'<img src="{_relpath(reports_dir, loss_png)}" style="max-width: 900px; width: 100%; border:1px solid #ddd; border-radius:8px;">'
    else:
        loss_html = '<p class="small">train_history.csv missing or no loss columns.</p>'

    eda_html = ""
    if eda_imgs:
        items = []
        for p in eda_imgs:
            rel = _relpath(reports_dir, p)
            items.append(f'<div><img src="{rel}"><div class="small">{p.name}</div></div>')
        eda_html = '<div class="imggrid">' + "".join(items) + '</div>'
    else:
        eda_html = '<p class="small">No EDA figures found.</p>'

    html = f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Surrogate Report - {cfg.package_name} - {run_id} - attempt_{attempt_num:03d}</title>
  <style>
    body {{ font-family: Segoe UI, Arial, sans-serif; margin: 22px; color: #1b1b1b; }}
    h1 {{ margin-bottom: 6px; }}
    .meta {{ color: #444; margin-bottom: 18px; }}
    .card {{ border: 1px solid #ddd; border-radius: 10px; padding: 14px 16px; margin: 12px 0; }}
    .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }}
    code {{ background: #f5f5f5; padding: 2px 6px; border-radius: 6px; }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ border: 1px solid #ddd; padding: 8px; font-size: 14px; }}
    th {{ background: #f2f6ff; text-align: left; }}
    .small {{ font-size: 13px; color: #555; }}
    .imggrid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; }}
    .imggrid img {{ width: 100%; border: 1px solid #ddd; border-radius: 8px; }}
  </style>
</head>
<body>

<h1>Surrogate Model Report</h1>
<div class="meta">
  <div><b>Run:</b> {run_id} &nbsp; | &nbsp; <b>Attempt:</b> attempt_{attempt_num:03d}</div>
  <div><b>Package:</b> {cfg.package_name}</div>
  <div><b>Generated:</b> {_utc_now()}</div>
</div>

<div class="card">
  <h2>Configuration</h2>
  <div class="grid">
    <div>
      <div><b>Inputs ({len(cfg.input_columns)}):</b></div>
      <div class="small">{", ".join(cfg.input_columns)}</div>
    </div>
    <div>
      <div><b>Outputs ({len(cfg.output_columns)}):</b></div>
      <div class="small">{", ".join(cfg.output_columns)}</div>
    </div>
  </div>
</div>

<div class="card">
  <h2>Artifacts</h2>
  <ul>
    <li><b>Model:</b> <code>{model_path}</code> ({'exists' if model_path.exists() else 'missing'})</li>
    <li><b>Weights JSON:</b> <code>{weights_path}</code> ({'exists' if weights_path.exists() else 'missing'})</li>
    <li><b>Metrics:</b> <code>{reports_dir / "metrics.json"}</code></li>
    <li><b>Training history:</b> <code>{train_history_csv}</code></li>
    <li><b>Modelica package:</b> <code>{modelica_pkg_dir}</code> ({'exists' if modelica_pkg_dir.exists() else 'missing'})</li>
    <li><b>Open in OMEdit:</b> <code>{package_mo}</code> ({'exists' if package_mo.exists() else 'missing'})</li>
    <li><b>Surrogate model file:</b> <code>{surrogate_mo}</code> ({'exists' if surrogate_mo.exists() else 'missing'})</li>
  </ul>
</div>

<div class="card">
  <h2>Training Metrics</h2>
  <p class="small">Physical metrics are computed by inverse-transforming scaled outputs using the saved y-scaler.</p>
  <table>
    <thead>
      <tr>
        <th>Output</th>
        <th>RMSE (physical)</th>
        <th>MAE (physical)</th>
        <th>RMSE (scaled)</th>
        <th>MAE (scaled)</th>
      </tr>
    </thead>
    <tbody>
      {metrics_rows if metrics_rows else "<tr><td colspan='5'>metrics.json not found or incomplete.</td></tr>"}
    </tbody>
  </table>
</div>

<div class="card">
  <h2>Loss Curves</h2>
  {loss_html}
</div>

<div class="card">
  <h2>EDA Figures</h2>
  {eda_html}
</div>

</body>
</html>
"""

    report_path = reports_dir / "report.html"
    report_path.write_text(html, encoding="utf-8")

    # NEW: copy report backup into modelica package folder
    backup_info = None
    if modelica_pkg_dir.exists():
        backup_info = _copy_report_backup(reports_dir=reports_dir, modelica_pkg_dir=modelica_pkg_dir)

    write_status(status_path, state="REPORT_DONE", message="Report generation complete.", progress=1.0)

    return {
        "timestamp_utc": _utc_now(),
        "run_id": run_id,
        "attempt": f"attempt_{attempt_num:03d}",
        "report_html": str(report_path),
        "loss_plot": str(loss_png) if loss_ok else None,
        "modelica_report_backup": backup_info,
    }
